extends:
- eslint:recommended
- plugin:jest/recommended
- plugin:prettier/recommended
env:
  es6: true
  node: true
parserOptions:
  ecmaVersion: 2018
overrides:
- files: "src/**/*.js"
  parserOptions:
    sourceType: module
