language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '9'
  - '8'
  - '6'
install:
  - yarn
script:
  - yarn test
after_success:
  - yarn semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
